[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 120

[tool.poetry]
name = "etest"
version = "1.1.0"
description = "Ebuild Testing Framework"
authors = [
  "Alex Brandt <alunduil@gmail.com>",
]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/alunduil/etest"
keywords = [
  "ebuild",
  "emerge",
  "gentoo",
  "portage",
  "test",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
    'Intended Audience :: Developers',
    'Intended Audience :: System Administrators',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: Implementation :: CPython',
    'Topic :: Software Development :: Quality Assurance',
    'Topic :: Software Development :: Testing',
    'Topic :: Utilities',
]
packages = [
  { include = "etest" },
]

[tool.poetry.dependencies]
click = "^7.1.2"
docker = "^5.0.0"
ply = "^3.11"
python = "^3.8"

[tool.poetry.dev-dependencies]
coveralls = "^2.1.1"
hypothesis = "^5.37.3"
pip = "^20.2.4"
pre-commit = "^2.7.1"
pytest = "^6.1.1"
pytest-cov = "^2.10.0"
vulture = "^2.0"

[tool.poetry.scripts]
etest = "etest:etest"

[tool.pytest.ini_options]
addopts = "--doctest-modules --cov=etest --cov-report=term-missing"
testpaths = [
  "etest_test",
]

[tool.skjold]
sources = [
  "pyup",
  "gemnasium",
]
