"""Metainformation for etest."""
AUTHOR = "Alex Brandt"
AUTHOR_EMAIL = "alunduil@gmail.com"
DESCRIPTION = "Ebuild Testing Framework"
LICENSE = "MIT"
NAME = "etest"
URL = "https://github.com/alunduil/etest"
VERSION = "1.0.0"
