# Copyright (C) 2014 by Alex Brandt <alunduil@alunduil.com>
#
# etest is freely distributable under the terms of an MIT-style license.
# See COPYING or http://www.opensource.org/licenses/mit-license.php.

import docker
import functools
import itertools
import logging
import os

from etest import overlay

logger = logging.getLogger(__name__)


class Test(object):
    def __init__(self, ebuild, test = False, **kwargs):
        self.ebuild = ebuild

        self.test = test

        self.use_flags = kwargs.get('use_flags', [])


        self.failed = False

        self.name = ebuild.name + '[' + ','.join(self.use_flags)
        if self.test:
            self.name += ',test'
        self.name += ']'

        self.environment = {}

        if 'python' in self.ebuild.compat:
            self.environment['PYTHON_TARGETS'] = ' '.join(self.ebuild.compat['python'])

        self.containers = []

        _ = 'alunduil/etest'
        self.docker_images = [
            _ + ':latest',
        ]

        c = docker.Client()
        c.pull(repository = _, tag = 'latest')

        self.commands = []

        if self.test:
            self.commands.append('echo {0} test >> /etc/portage/package.env'.format(ebuild.name))

        self.commands.append('echo {0} {1} >> /etc/portage/package.use'.format(ebuild.name, ' '.join(self.use_flags)))
        self.commands.append('emerge -q {0} --autounmask-write'.format(ebuild.name))
        self.commands.append('etc-update --automode -5')
        self.commands.append('emerge -q {0}'.format(ebuild.name))

        self.commands.extend(kwargs.get('commands', []))

    def clean(self):
        c = docker.Client()

        for container in self.containers:
            c.remove_container(container)

        for docker_image in self.docker_images:
            c.remove_image(docker_image)

    def run(self):
        repository = 'etest/' + self.name

        c = docker.Client()

        for command in self.commands:
            self.containers.append(uuid.uuid4())
            c.create_container(
                image = self.docker_images[-1],
                name = self.containers[-1],
                environment = self.environment,
                volumes = [
                    '/usr/portage',
                    '/overlay',
                ],
                entrypoint = '/bin/bash',
                command = command,
            )

            c.start(
                container = self.containers[-1],
                binds = {
                    self.ebuild.overlay.directory: {
                        'bind': '/overlay',
                        'ro': True,
                    },
                    # TODO: Retrive this from environment.
                    '/usr/portage': {
                        'bind': '/usr/portage',
                        'ro': True,
                    },
                },
            )

            tag = self.commands.index(command)

            self.docker_images.append(repository + ':' + tag)
            c.commit(
                self.containers[-1],
                repository = repository,
                tag = tag,
            )


class Tests(object):
    def __init__(self, ebuild_filter = ()):
        self.overlay = overlay.Overlay()

        # NOTE: raises InvalidOverlayError when necessary
        logger.debug('self.overlay.directory: %s', self.overlay.directory)

        self.ebuild_filter = [ _.replace('.ebuild', '') for _ in ebuild_filter ]

        if not len(self.ebuild_filter):
            logger.debug('os.getcwd(): %s', os.getcwd())
            logger.debug('os.path.relpath(self.overlay.directory): %s', os.path.relpath(self.overlay.directory))

            _ = os.path.relpath(self.overlay.directory)

            if _.startswith('..'):
                self.ebuild_filter.append(os.getcwd().replace(self.overlay.directory, '').strip('/'))

    @property
    def tests(self):
        if not hasattr(self, '_tests'):
            logger.info('STARTING: populate tests')

            self._tests = []

            for ebuild in self.overlay.ebuilds:
                if not len(self.ebuild_filter) or any([ _ in ebuild.name for _ in self.ebuild_filter ]):
                    self._tests.extend(self._generate_tests(ebuild))

            logger.info('STOPPING: populate tests')

        return self._tests

    def _generate_tests(self, ebuild):
        '''Generate all tests for a given ebuild.

        Prepare all tests for a given ebuild so they are ready to be run.  This
        includes finding the powerset of the USE flags and creating a runtime
        for each combination among other things.  It also includes setting
        appropriate environment variables (i.e. PYTHON_TARGETS=PYTHON_COMPAT).

        .. note::
            Later, we will add support for a test specification file to modify
            the set of tests generated by this function.

        Arguments
        ---------

        :``ebuild``: Ebuild to inspect and create various test cases for

        Returns
        -------

        Tuple of Test objects.

        '''

        logger.info('STARTING: generate tests for %s', ebuild.name)

        tests = []

        use_flags = list(ebuild.use_flags)
        use_flags.remove('test')

        logger.debug('ebuild.use_flags: %s', ebuild.use_flags)

        for use_flags_combination in itertools.chain.from_iterable(itertools.combinations(use_flags, _) for _ in range(len(use_flags) + 1)):
            logger.info('adding %s[%s]', ebuild.name, ','.join(use_flags_combination))

            tests.append(Test(ebuild, use_flags = use_flags_combination))

            logger.info('adding %s[test,%s]', ebuild.name, ','.join(use_flags_combination))

            tests.append(Test(ebuild, test = True, use_flags = use_flags_combination))

        logger.info('STOPPING: generate tests for %s', ebuild.name)

        return tests
